services:
  securion-sphere-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL
    networks:
      - securion-frontend

networks:
  securion-frontend:
    driver: bridge
    name: securion-frontend
    external: true
