services:
  securion-sphere-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NEXT_PUBLIC_GOOGLE_MAP_KEY
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - NEXT_PUBLIC_BACKEND
    env_file:
      - .env.development.local
      - .env.local
    networks:
      - securion-frontend

networks:
  securion-frontend:
    driver: bridge
    name: securion-frontend
    external: true
