name: Deploy dev to Self-Hosted

on:
  workflow_run:
    workflows: ["Run Lint and Build"]
    branches: ["main"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to dev
    runs-on: ["self-hosted", "pau-proj-prod"]
    environment: prod
    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Build the docker-compose stack
        run: docker compose -f docker-compose.prod.yml up -d --build
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

      - name: Clear all docker unused cache
        run: docker system prune -af
